Fix no delete share memory
duncan3dc/fork-helper pull request #6
Opened 2016-11-18 06:00 UTC by eaglewu

Missing call `shaop_delele()` in `getExceptions`  when the closure function is done without any exceptions in PcntlAdapter.

2016-11-18 09:39 UTC, duncan3dc commented
@eaglewu Thanks for contributing, it seems like a good idea to clean up the memory after use, but I'm not sure this is the best way to go about it, let me take a look

2016-11-18 09:40 UTC, duncan3dc requested changes

2016-11-18 09:40 UTC, duncan3dc commented on composer.json
> +    "name": "eaglewu/fork-helper",
@eaglewu It looks like you've accidentally pushed some other changes here.

2016-11-18 09:40 UTC, duncan3dc commented on src/Fork.php
> +        $exceptions = $this->adapter->getExceptions();
@eaglewu It's a little odd to call this here, what do you think about handling it in [SharedMemory](https://github.com/duncan3dc/fork-helper/blob/a253b551dfd98ef70307a2858c6b39cab4431235/src/SharedMemory.php#L8) using a [destructor](http://php.net/manual/en/language.oop5.decon.php#language.oop5.decon.destructor)?

2016-11-19 05:09 UTC, wudi commented on src/Fork.php
> +        $exceptions = $this->adapter->getExceptions();
Sorry! my mistake, i will push new request shot now.

2016-11-19 18:33 UTC, duncan3dc commented
@eaglewu You don't need to create a new pull request, you can use [git rebase](https://help.github.com/articles/about-git-rebase/) to change the commits you've already pushed and remove ones you no longer want

2016-11-21 04:00 UTC, eaglewu commented
@duncan3dc I got some other problems with the commit, Is not the best way to go about it,So let me take a look.

2017-03-01 06:38 UTC, sergeyklay commented
@eaglewu ping

2017-06-01 13:28 UTC, martijnhartlief commented
After using this for a while I get this:
`Warning: shmop_open(): unable to attach or create shared memory segment 'No space left on device' `

When you call:
`$ ipcs -m`
You'll see a huge list of memory sections claimed by the forker.
Even restarting PHP-FPM won't free the memory.

Any chance this can be picked up again?

2017-06-01 13:47 UTC, duncan3dc commented
Hi @martijnhartlief, please open a new issue to report your problem, then we can investigate it there

2017-07-11 20:18 UTC, duncan3dc commented
This is fixed in version `2.2.0` now, as long as you call `wait()` the shared memory will be deleted

2017-07-11 20:18 UTC, closed without merging